-- Generated by nwg-displays on 2026-08-13 at 11:09:49. Do not edit manually.

hl.monitor({
    output = "DVI-D-1",
    mode = "1920x1080@60.0",
    position = "0x0",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1280x960@60.0",
    position = "1920x313",
    scale = 2.0
})
